
# Utilizar la imagen oficial de PostgreSQL
FROM postgres:latest

# Variables de entorno para configurar PostgreSQL
ENV POSTGRES_USER=postgres
ENV POSTGRES_PASSWORD=postgres


# Puerto en el que escuchará PostgreSQL (por defecto es 5432)
EXPOSE 5432

# Comando para iniciar PostgreSQL
CMD ["postgres"]